name: Substitue variable
description: Substitute variables for JSON/XML - first release will support JSON
inputs:
  repo:
    required: false
    default: ${{ github.repository }}
  token:
    required: false
    default: ${{ github.token }}  
  type:
    required: true
    default: ''
  
outputs:
  version:
    description: version
runs:
  using: "node16"
  main: src/convert.js